using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

[assembly: AssemblyCompanyAttribute("NJM Insurance Group")]
[assembly: AssemblyCopyrightAttribute("(c) 2005 NJM Insurance Group")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyConfigurationAttribute("Release")]
[assembly: AssemblyProductAttribute("Imaging Web Service")]
[assembly: AssemblyVersionAttribute("2.0.1.0")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AssemblyKeyFileAttribute("")]
[assembly: AssemblyKeyNameAttribute("")]
[assembly: AssemblyTitleAttribute("EnterpriseImaging.ImagingServices.ServiceInterface")]
[assembly: AssemblyDescriptionAttribute("Imaging Web Service")]

